### ISSUE TITLE
adding PostCSS plugins?

### ISSUE THREAD

**Issue by paOol** [egoist/vuepack#105]
trying to use PostCSS autoprefixer and get CSS variables in my dev/production.

In `webpack.dev.js` I tried adding

`require('postcss-advanced-variables')`

and 

```

// push loader for .css file
base.module.loaders.push(
  {
    test: /\.css$/,
    loaders: ['style-loader', _.cssLoader, 'postcss-loader', 'postcss-advanced-variables']
  }
)
```

but it didn't work so where is the right place to place it?
I did npm install postcss-advanced-variables .

**Comment by egoist** [comment]
https://github.com/egoist/vuepack/blob/master/template/build/config.js
