### ISSUE TITLE
Access components from common root

### ISSUE THREAD

**Issue by bryaan** [egoist/vuepack#109]
Directory Structure:

```
/components
  /Button
    /index.js
/About
  /index.js

```
In my `About/index.js` file I want to do:

```js
import Button from 'components/Button' 
```
instead of:

```js
import Button from '../components/Button' 
```
Which can quickly become a problem for large apps requiring multiple walks back up the directory tree.

How can I set this up?

**Comment by egoist** [comment]
It's already enabled for you https://github.com/egoist/vuepack/blob/master/template/build/webpack.base.js#L31

**Comment by bryaan** [comment]
awesome thanks!
