### ISSUE TITLE
Scoped CSS is not working properly when extracted into a single file.

### ISSUE THREAD

**Issue by egoist** [egoist/vuepack#11]
Known issue.

**Comment by piotrekfracek** [comment]
Any solution @egoist ?

I've seen [here](https://github.com/vuejs/vue-loader/issues/119) that you found what caused issue.

**Comment by egoist** [comment]
Well, I still have no idea, but remove [`precss`](https://github.com/egoist/vuepack/blob/59387c3502ba8f5dc0ebc1316cfea3c073056eca/scripts/webpack.config.js#L28) here solves it.
