### ISSUE TITLE
How to use with vbuild

### ISSUE THREAD

**Issue by bryaan** [egoist/vuepack#110]
Docs say they recommend using vbuild.

How can I do that?

I assume it's something simple like:
```

yarn global add vbuild

vbuild index.js --dev // What should this be?

```

**Comment by egoist** [comment]
Check out the README at https://github.com/egoist/vbuild

It's not necessary to use vbuild with this template, you can run `vbuilt init my-project` to generate one or create an entry file by hand.

`
vbuild index.js --dev` this means using `index.js` as entry file and run vbuild in dev mode.

**Comment by bryaan** [comment]
I'd like to use it.  Is the entry file a simple thing?  Have any example?

**Comment by egoist** [comment]
Here it is https://github.com/egoist/vbuild#how-to-use

**Comment by bryaan** [comment]
Im sorry, I don't get it.  Nothing vbuild specific in the file there.  What am I missing?

**Comment by egoist** [comment]
It's just a webpack wrapper for better development experience.

**Comment by bryaan** [comment]
should I be running with `vbuild ...` instead of `yarn run dev`?  

or is it a line to add somewhere?

or all i need is a `vbuild.config.js`?

**Comment by egoist** [comment]
`yarn run dev` === `npm run dev` so you can configure npm scripts to run vbuild as well

**Comment by bryaan** [comment]
I tried : `vbuild ./client/index.js --dev
`
```
ERROR in ./client/views/Home/index.js
Module not found: Error: Can't resolve 'components/Counter' in '/app/client/views/Home'
 @ ./client/views/Home/index.js 1:0-41
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi /usr/local/share/.config/yarn/global/~/vbuild/lib/dev-client.es6 ./client/index.js
```

**Comment by egoist** [comment]
Try `vbuild.config.js`:

```js
const path = require('path')

module.exports = {
  entry: './client/index.js',
  postcss: [
    require('postcss-nested')
  ],
  webpack: {
    resolve: [path.resolve('client')]
  }
}
```

```bash
vbuild --dev -c
```

**Comment by bryaan** [comment]
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve should be an object.
```

**Comment by egoist** [comment]
Hmm sorry: 

```js
webpack: {
  resolve: {
    modules: [path.resolve('client')]
  }
}
```

**Comment by egoist** [comment]
Why would you not try the `vbuild init` command instead?

**Comment by bryaan** [comment]
Thank you!

Actually I was going to ask about that.  This doesn't seem to work: `vbuild init my-project`

`-bash: vbuild: command not found
`
And that is after running: `yarn global add vbuild`


Just for ref this worked:
```js

const path = require('path')

module.exports = (options, req) => ({
  entry: './client/index.js',
  postcss: [
    require('postcss-nested')
  ],
  webpack: {
    resolve: {
      modules: [path.resolve('client')]
    }
  }
})
```

**Comment by bryaan** [comment]
It was a simple error on my side.  What command do I run to use this as the template?

**Comment by bryaan** [comment]
On an unrelated note:  Is enabling JSX the modern way to go with Vue?  And is it fine to use this in combo with regular Vue templates?

**Comment by egoist** [comment]
> It was a simple error on my side. What command do I run to use this as the template?

No, it's not recommend to use this template in vbuild, however it can be. here's a lot of boilerplate code

> Is enabling JSX the modern way to go with Vue?

JSX or template, you can only use one of them in a component.

**Comment by bryaan** [comment]
> No, it's not recommend to use this template in vbuild, however it can be.

So are you saying I should just use the vbuild template and ignore this starterkit?

Im pretty sure that's not the case so what would I do with `vbuild init`?  You mean to use it to just create the config file?

**Comment by egoist** [comment]
Just try `vbuild init` and you'll get it

**Comment by bryaan** [comment]
What I'm getting is a new barebones project but it has nothing to do with this starter kit.  I really don't get what I'm supposed to be seeing... 

Also, I made a mistake about it working.  It says it compiled successfully but I cannot access it in browser anymore.

**Comment by egoist** [comment]
I don't know why you think vbuild has something to do with this template 😂

**Comment by bryaan** [comment]
I'm really confused as to why your saying I should use `vbuild init`

**Comment by egoist** [comment]
If you want to work with webpack directly, use this template or other vue-cli template

If you want your project to be clean and develop it with almost no configuration, try vbuild. `vbuild init` gives you a basic project folder with your app's entry file and `vbuild.config.js` so that you don't need to create them manually.

**Comment by bryaan** [comment]
I think I see.  So I have to do a kind of merge between that initial structure and this project?

**Comment by bryaan** [comment]
Do you have any idea why it's not loading in browser?

**Comment by egoist** [comment]
you can totally replace the `src` folder with the `client` folder in this template. The folder structure does not really matter.

**Comment by bryaan** [comment]
and package.json?

**Comment by egoist** [comment]
sure no, that the purpose of vbuild, you can get rid of the crazy list of dependencies in package.json, only include what you need

**Comment by bryaan** [comment]
Ok, so given everything said here, what exactly is the 'recommended' use case of vbuild with this starter kit?
