### ISSUE TITLE
Why deps are in dev deps?

### ISSUE THREAD

**Issue by seemsindie** [egoist/vuepack#12]
Just a question, why are dependencies that are not dev dependencies in devDependencies?
I am talking about vue, moment...

**Comment by egoist** [comment]
I'm not sure.

For an SPA all deps are only needed during development. IMO.

Feel free to correct me 😀

**Comment by egoist** [comment]
I think you are right, fixed this. 🙂

**Comment by seemsindie** [comment]
@egoist thanks :)
