### ISSUE TITLE
how to assign css files to a folder,and the url referenced correctly wirte in?

### ISSUE THREAD

**Issue by cddsgtc** [egoist/vuepack#123]

**Comment by egoist** [comment]
Hi, I don't really understand your question but it seems like a general webpack question, feel free to ask it on stackoverflow and such.

**Comment by cddsgtc** [comment]
@egoist 
e。。。。
i want do some thing like this.
```
...
{
test:/\.css$/,
loader:['css-loader'],
query:{
//this is the point i mean.
name:'dist/css/[name].[ext]?[hash:10]'
}
}
```

**Comment by egoist** [comment]
Check out https://github.com/egoist/vuepack/blob/master/template/build/webpack.prod.js#L29

**Comment by cddsgtc** [comment]
@egoist 
thank you so much. i remember it. thank you again.
