### ISSUE TITLE
Switching between electron mode vs browser mode

### ISSUE THREAD

**Issue by franciscolourenco** [egoist/vuepack#124]
When Electron mode is selected, is it possible to switch back and forth between browser and electron?

**Comment by egoist** [comment]
You can set `electron` to `false` in `./build/config.js`

**Comment by franciscolourenco** [comment]
Would it be possible to have an env variable?

**Comment by egoist** [comment]
do you mean `electron: process.env.ELECTRON` ?

**Comment by franciscolourenco** [comment]
I was just thinking of a way for it to support it by default. thanks
