### ISSUE TITLE
Webpack Define Plugin is not working

### ISSUE THREAD

**Issue by BojDom** [egoist/vuepack#126]
If you clone your repo  everything is working except that i can't pass to the client.js some variables.
If you make npm run build and view the source of the client.js file you will not find the process.env.NODE_ENV variable for example... please fix this issue

**Comment by egoist** [comment]
Just tried, it's actually working for me... sure you can't find `process.env.NODE_ENV` because it's replaced with `"production"`

**Comment by BojDom** [comment]
I just realized that the define plugin is just a text replacer... so it does not fill variables in an object, i must call that variable with the exact string added in the define plugin
