### ISSUE TITLE
Routes not working in production

### ISSUE THREAD

**Issue by zeeshanjan82** [egoist/vuepack#138]
Hi, I have really liked this seed project. However when I run the command `npm run build` everything works fine and I see the complied result in dist folder. I have added couple of new routes, views and components. After the compilation is done. When I try running the files from the dist folder I only see the Home page, when I try navigating to other pages it gives a 404 error.

**Comment by egoist** [comment]
You need to serve `dist` folder with a static server, like using https://github.com/zeit/serve

**Comment by zeeshanjan82** [comment]
@egoist actually I am already using static server: https://www.npmjs.com/package/live-server  inside dist folder. Everything work fine in development but when I run the command `live-server` inside the dist folder only Home view is shown and when I navigate to other views in the route then I get  a 404 error.

**Comment by egoist** [comment]
Are you using history mode in vue-router? Providing a minimal repo to reproduce this would be helpful.

**Comment by zeeshanjan82** [comment]
@egoist yes that is actually the issue. I was using history mode instead of hash. But what if I would like to use history mode is there any thing I can do to fix this issue. It comes only in history mode

**Comment by zeeshanjan82** [comment]
@egoist got it I found some info here: https://router.vuejs.org/en/essentials/history-mode.html

**Comment by frostini** [comment]
thanks for pointing that out @zeeshanjan82 !
For others that may run into the issue, the `https://github.com/bripkens/connect-history-api-fallback` does the trick or you can also manually set a catch-all route and redirect to index for vue router to parse. This is how it could be implemented in express:

_serving static build through root (*using `serve-static` npm)_
 ```
app.use("/", serveStatic ( path.join (__dirname, '/dist') ) )
```
_manual catch-all_
```
app.get('*', function (req, res) {
    res.sendFile(__dirname + '/dist/index.html')
})
```
PS. for newbies, remember to do a `npm run build` prior to depoyment to include the latest changes !
