### ISSUE TITLE
Missed packages

### ISSUE THREAD

**Issue by korjavin** [egoist/vuepack#139]
```
    "timers-browserify":"^2.0.0",
    "strip-ansi":"^4.0.0",
    "ansi-html":"^0.0.7",
    "html-entities":"^1.2.0",
    "ansi-regex":"^3.0.0",
    "setimmediate":"^1.0.5"
    "vue-style-loader": "^1.0.0",

```

**Comment by egoist** [comment]
Hmm what?

**Comment by korjavin** [comment]
I followed the insruction, 
vue init..
npm install , etc

But it `npm run build' kept showing me errors about those packages untill I put them into packajes.json and did npm install

**Comment by egoist** [comment]
what's your node/npm version?

**Comment by korjavin** [comment]
> npm --version
1.4.21
> node --version        
v4.8.2

**Comment by egoist** [comment]
Check out the README, `npm@3` is the minimal version it supports.
