### ISSUE TITLE
Explain how to serve/dist static files

### ISSUE THREAD

**Issue by mattattui** [egoist/vuepack#14]
Sorry I'm a relative newbie, but it's not at all clear to me how to make the dev server serve static files (in my case I have some `.json` files from json-generator.com to mock an API) or how to have these files included in the output of `npm run build`. Could you add something in the README on how to achieve this?

**Comment by egoist** [comment]
Hi, I've updated the [scripts/devServer.js](https://github.com/egoist/vuepack/blob/master/scripts/devServer.js) to make it more customizable, you can update [scripts/wrap.js](https://github.com/egoist/vuepack/blob/master/scripts/wrap.js) to do whatever you want now.

README.md will be updated later. 😅

**Comment by mattattui** [comment]
Marvellous, thanks!
