### ISSUE TITLE
i create project npm run app electron empty.!!

### ISSUE THREAD

**Issue by rondaful** [egoist/vuepack#143]
vue-cli egoist/vuepack new-project

npm install

npm run dev

npm run build

npm run app

open electron window .
  but electron window is empty.
![_20170802003015](https://user-images.githubusercontent.com/30513851/28835998-e82a2a76-7719-11e7-95e7-e2ff2546f824.png)

**Comment by rondaful** [comment]
platfrom : window 7
node 8

**Comment by rondaful** [comment]
when 
I   npm run dev
   npm run app

npm run dev window print waiting comping!!!! on window 7 64

**Comment by egoist** [comment]
Fixed.
