### ISSUE TITLE
HOT Reload is not working

### ISSUE THREAD

**Issue by rajeevbbqq** [egoist/vuepack#154]
When i made an update on *.vue file in components , there is no change detected on browser if refreshes manually too.An if i need to update i have to re run ` npm run dev`

**Comment by egoist** [comment]
What changes did you made to the file? Please provide a repro.
 (not all changes can be hot reloaded) It's simply using vue-loader for hot reload.

**Comment by rajeevbbqq** [comment]
Nothing changed.Just installed this boilerplate

**Comment by rajeevbbqq** [comment]
I simply ran `sudo npm run dev` instead of `npm run dev` and my hassle gone ! Thanks @egoist for this wonderful wrapper. 

NB : I'm working on Ubuntu
