### ISSUE TITLE
Add vendor css and js in webpack

### ISSUE THREAD

**Issue by sotaan** [egoist/vuepack#18]
Hey,
I managed to add a _vendor.js_ file in the stack like this:
1. inside **webpack.config.js**:
   -  entry become:
   
   ```
   entry: {
       app:    ['./src/main.js'],
       vendor: ['sweetalert', 'jquery']
     }
   ```
   -  add this in the plugin list:
   
   `new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.js", Infinity),`
2. inside **webpack.config.dev.js**:
   `config.entry.push('webpack-hot-middleware/client')`
   become this:
   `config.entry.app.push('webpack-hot-middleware/client')`

My problem is: how to achieve the same with my css vendor files from the _node_modules_ directory?

**Comment by egoist** [comment]
Maybe this can help you: http://survivejs.com/webpack/building-with-webpack/separating-css/

**Comment by sotaan** [comment]
Sorry for the long time without posting any response.
Just checked your link and it look like a good way to solve the problem; I will try it today ASAP and then post a feedback.
Thanks for your awesome stack, it really helped me getting started to Vue.js development!

**Comment by egoist** [comment]
@sotaan you're welcome, just keep going with Vue 😬
