### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by teameh** [egoist/vuepack#2]
Installed following instructions: 

```
$ npm install -g vuepack
/usr/local/bin/vue -> /usr/local/lib/node_modules/vuepack/bin/vuepack
/usr/local/lib
└── vuepack@0.1.4
```

Looks all fine right? But apparently somethings is not. 

```
$ vue init hello-vue
env: node\r: No such file or directory

$ vue --version
env: node\r: No such file or directory

$ vue --help
env: node\r: No such file or directory
```

Any idea's? Seems [more](https://github.com/nwjs/nw-builder/issues/75) people are [struggling](http://stackoverflow.com/questions/30630211/i-keep-getting-env-node-no-such-file-or-directory-running-grunt-on-eclipse-a) with [this](https://github.com/Automattic/juice/issues/118)..

```
$ node --version
v5.0.0

$ which node
/usr/local/bin/node

$ npm --version
3.3.12

$ which npm
/usr/local/bin/npm
```

**Comment by egoist** [comment]
does `:set ff=unix` work for you?

if not you can `git clone https://github.com/egoist/vuepack-cli` and `npm link` by hand

I'll fix that later.

**Comment by egoist** [comment]
I've fixed it, just reinstall the `vuepack` to check out. 😗

**Comment by teameh** [comment]
That did the trick, thank you for the quick fix 👋
