### ISSUE TITLE
Running into issues with the router and using an external component for the nav

### ISSUE THREAD

**Issue by chopfitzroy** [egoist/vuepack#21]
Full source [here](https://github.com/CrashyBang/portfolio).

I am receiving the following error by having my navigation menu as an external component:

```
[Vue warn]: Failed to resolve directive: link (found in anonymous component - use the "name" option for better debugging messages.))
```

Now after a bit of googling I think it is related to [this](https://github.com/vuejs/vue/issues/603).

Which is something to do with the component being external.

**App.vue**:

``` vue
<template>
  <div id="app">
    <div class="container">
      <navigation></navigation>
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
import Navigation from './components/Navigation'

export default {
  components: {
    Navigation,
  }
}
</script>
```

**Navigation.vue**:

``` vue
<template>
  <div class="navigation">
    <div class="grid -middle">
      <div class="cell -3of12">
        <h1>Otis Wright</h1>
      </div>
      <div class="cell -9of12">
        <ul class="menu">
          <li>
            <a v-link="{ path: 'home' }">Home</a>
          </li>
          <li>
            <a v-link="{ path: '/projects' }">Projects</a>
          </li>
          <li>
            <a href="#">Experiments</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
```

But after looking at the `routes` I can not figure out what is going wrong?

**index.js**:

``` js
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  mode: 'hash',
  routes: [
    {
      path: '/',
      component: require('../views/Home')
    },
    {
      path: '/projects',
      component: require('../views/Projects')
    }
  ]
})
```

Sorry still learning Vue and I am probably missing something really simple, the routes are being handled slightly differently to what I am used to so I can't quite figure it out.

**Comment by LucasIcarus** [comment]
"Failed to resolve directive: link (found in anonymous component)"

Haven't see this bug report before, but you sure about your Home.vue and Projects.vue are correct ?

In `routes/index.js`, when the routes of Router instance be rendered as `<router-view>` component, in Vue's debug system it is anonymous. Maybe follow the lint add the name attr to routes in `routes/index.js` or deal it with Chrome vue-devtools will help.

**Comment by egoist** [comment]
Do not use `require('../views/Home')`, instead:

``` js
import Home from '../views/Home'

export default new Router({
  //...
  routes: [
    {
      path: '/',
      component: Home
    },
    //...
  ]
})
```

I don't know what goes wrong indeed, maybe related to the loader or something.

**Comment by egoist** [comment]
Oh, I misunderstand you.

There's no `v-link` directive in `vue-router` 2

Using a component called `<router-link>` instead:

``` js
<router-link to="/">/</router-link>

```

**Comment by chopfitzroy** [comment]
Hey @egoist thank you! I did wonder if it was something like that!

Cheers.

**Comment by wanteed-lh** [comment]
@egoist i try this solution but dosn't work with 
that my error 
[Vue warn]: Failed to resolve directive: link 
(found in anonymous component - use the "name" option for better debugging messages.)
