### ISSUE TITLE
vue-cli template

### ISSUE THREAD

**Issue by zigomir** [egoist/vuepack#22]
Hi,

`vuepack` seems nice! Why not pack it inside `template` directory so one can use it with `vue-cli`? I'm just curios is this is by design or you'd accept `vue-cli` compatibility PR?

**Comment by egoist** [comment]
this was made much earlier than vue-cli, vuepack ever had a cli tool too, but had been deprecated since vue-cli was created.

if you can make a PR, i think it's fine for me 😊
