### ISSUE TITLE
Using vuepack with Socket.io

### ISSUE THREAD

**Issue by p-adams** [egoist/vuepack#24]
Is it possible to integrate this with something like socket.io? Is there anything special I'd need to do with webpack-dev-server?

**Comment by egoist** [comment]
Here we didn't use webpack-dev-server, but a standalone [server.js](https://github.com/egoist/vuepack/blob/master/build/server.js) (only for dev purpose) , this is just a client-side boilerplate, so you can integrate it with any backend.

**Comment by p-adams** [comment]
Awesome. Thanks!
