### ISSUE TITLE
Errors in app.js client

### ISSUE THREAD

**Issue by p-adams** [egoist/vuepack#25]
Upon generating a new project, I get three errors in the ./client/app.js file:

Regarding

`const app = new Vue({
  router,
  store,
  ...App
})`

The follow errors: 
`Property assignment expected`
`"," expected`
`Declaration or statement expected`

There are also quite a few errors showing up in ./client/components/App/style.css

**Comment by egoist** [comment]
Where did you see these errors? It looks like some eslint errors, if so you can modify the code to suit your own need.

**Comment by p-adams** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17172384/17643486/9410c13a-6139-11e6-9138-8610c76843da.png)
I am seeing the errors in Visual Studio. They appear to be syntax errors. The other error I see is when I 
`cd build` -> `node server.js` to run the server from there: `ERROR in multi client
Module not found: Error: Can't resolve './client/index.js' in 'C:\home\new-project\build'
 @ multi client
`
This might be unrelated. I am not familiar enough with webpack to know what is going on here.

**Comment by egoist** [comment]
For the syntax error, please refer to https://code.visualstudio.com/docs/languages/javascript , add `jsconfig.json` to make vscode aware of es6.

For the build error, you should run commands in project root directory or run `npm run dev` to start dev server. the `pwd` is important for Webpack to resolve files.

**Comment by p-adams** [comment]
Okay, must just be a VS thing. Weird since VS no longer requires jsconfig.json to make it aware of es6.
