### ISSUE TITLE
开发环境autoprefixer加的前缀数量和生产环境中不一致

### ISSUE THREAD

**Issue by agileago** [egoist/vuepack#27]
开发环境 
![image](https://cloud.githubusercontent.com/assets/11799110/18022243/c1fedae6-6c1f-11e6-9524-1d6ea4364327.png)

开发环境的css前缀数量是正确的
![image](https://cloud.githubusercontent.com/assets/11799110/18022255/e089499c-6c1f-11e6-8459-8c8f0af3062f.png)

但是生产环境打包出来的就少了，随机减少，怀疑是`extract-text`插件引起的
![image](https://cloud.githubusercontent.com/assets/11799110/18022212/94e95c5c-6c1f-11e6-9b62-8fdaad22307b.png)

**Comment by egoist** [comment]
See https://github.com/postcss/autoprefixer#no-prefixes-in-production, fixed.

**Comment by agileago** [comment]
@egoist it seems not work. do you test it ?  maybe it is a bug of webpack2 minify plugin

**Comment by agileago** [comment]
@egoist    https://github.com/postcss/autoprefixer/issues/660#issuecomment-220808316
