### ISSUE TITLE
Dev mode is broken for electron

### ISSUE THREAD

**Issue by jreyes** [egoist/vuepack#28]
Hello! Selecting electron and running the dev script runs the server but when i try to load the project i get a 

> Cannot GET /

**Comment by egoist** [comment]
Did you open the browser? there's no need to open browser for Electron, `npm run app` instead.

**Comment by jreyes** [comment]
thanks for the help, that was the answer. Wasn't aware that I needed to run the app to use the dev mode too.  Thanks!
