### ISSUE TITLE
should add webpack alias to vue/dist/vue

### ISSUE THREAD

**Issue by hisland** [egoist/vuepack#32]
i can not run the [very basic start example](http://rc.vuejs.org/guide/index.html#Declarative-Rendering)

from the [Note-on-NPM-Builds](http://rc.vuejs.org/guide/installation.html#Note-on-NPM-Builds), i think you should add webpack alias to vue/dist/vue

but i think maybe this template is for vue2+vuex2+vue-router2, not for very basic usage,
 just mark here for others basic user when encounter the problem

**Comment by egoist** [comment]
Yep, since we only consider the situation using single-file component here, I guess we don't need to support the `template` option.
