### ISSUE TITLE
Replace precss with individual plugins

### ISSUE THREAD

**Issue by dodas** [egoist/vuepack#33]
Since precss [seems to be unmaintained](https://github.com/jonathantneal/precss/issues/84), and have issues, I think it would be appropriate to ditch it and require individual plugins.

For example, today I experienced problem where plugin `postcss-extend` should be used after plugin `postcss-nested` - see [Public Service Announcement](https://github.com/travco/postcss-extend) under `Instalation`, but precss have it in incorrect order.

**Comment by egoist** [comment]
I'd like to replace them with some better alternatives, do you have any suggestions about what should be included? PRs are welcome too 🙂

**Comment by dodas** [comment]
Starting with precss,

I removed:

`postcss-custom-properties` - already have Sass-like `postcss-advanced-variables`, and cascading feature of custom properties cannot be mimicked / transformed to CSS3.
`postcss-nested` - already have Sass-like `postcss-nested` which does not require `&` everywhere.
`postcss-atroot` - I don't see usefulness with Vue component, as everything should be under component's namespace. But maybe someone would find it useful.
`postcss-custom-selectors` - I just don't use it.

And I added:

`postcss-nested-ancestors` - I use it to reference parent selector combined with state selector. Example:

```
.entry {
  ...

  &-info {
    display: none;

    ^&.is-selected & {
      display: block;
    }
  }
}
```

outputs:

```
.entry {
  ...
}

.entry-info {
   display: none;
}

.entry.is-selected .entry-info {
  display: block;
}
```

I think it's nice.. :)

And this is the order which I require plugins in:

```
require('postcss-nested-ancestors'),
require('postcss-partial-import'),
require('postcss-mixins'),
require('postcss-advanced-variables'),
require('postcss-custom-media'),
require('postcss-media-minmax'),
require('postcss-color-function'),
require('postcss-extend'),
require('postcss-nested'),
require('postcss-property-lookup'),
require('postcss-selector-matches'),
require('postcss-selector-not'),
```

Should I make a PR?

**Comment by egoist** [comment]
I just realized I did't use any postcss plugin specified syntax in the CSS, maybe we can simply remove precss and let user choose what plugins they want.

**Comment by dodas** [comment]
Yup, that would probably be nicest way.
