### ISSUE TITLE
Is gh-pages something that is supposed to exist globally on my system?

### ISSUE THREAD

**Issue by chopfitzroy** [egoist/vuepack#36]
I notice you have the following line in the `package.json`'s scripts block:

``` json
"gh": "npm run build && gh-pages -d dist"
```

But `gh-pages` is not a dependency is this installed globally?

Cheers.

**Comment by egoist** [comment]
There was a demo for vuepack, that's why this scripts exists. I used to use gh-pages as a global CLI but it often runs into issues, so it would be better to be used as a devDependency, but this script should be removed since we no longer need to deploy a demo .
