### ISSUE TITLE
Styles not applied using JSX mode by default

### ISSUE THREAD

**Issue by legendtang** [egoist/vuepack#37]
If chose JSX in the cli, the counter won't get any styles.

**Comment by egoist** [comment]
Seems css-modules is not enabled by default in JSX mode, you could turn on css-modules in webpack config or load css in normal way as a workaround for now.

``` diff
-import style from './style.css'
+import './style.css'

 export default {
   methods: {
@@ -8,9 +8,9 @@ export default {
   },
   render(h) {
     return (
-      <div class={style.counter} on-click={this.handleClick}>
+      <div class="counter" on-click={this.handleClick}>
         {this.$store.state.count}
       </div>
     )
   }
-}
```

However, to avoid global classnames, it's recommended to enable css-modules in JSX mode.

I would fix it later.

**Comment by egoist** [comment]
Fixed, now css-modules is enabled by default, [docs/css-modules](https://github.com/egoist/vuepack/blob/master/docs/css-modules.md).
