### ISSUE TITLE
Hot Module Replacement doesn't work.

### ISSUE THREAD

**Issue by legendtang** [egoist/vuepack#39]
```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
[HMR]  - ./client/views/Home/index.js
```

It seems `module.hot.accept()` should be added to somewhere on parent. I'm not a webpack expert.

**Comment by egoist** [comment]
Yep, currently only single-file components has built-in hot reloading support, personally I add a [webpack-livereload-plugin](https://www.npmjs.com/package/webpack-livereload-plugin) while using jsx. I'm also looking forward to someone could make [this](https://github.com/vuejs/vue-requests/issues/18).
