### ISSUE TITLE
Splitting vendor chunk

### ISSUE THREAD

**Issue by dodas** [egoist/vuepack#40]
Hello, this issue is question.

Why do we split bundle into "vendor" and "client" files?
And then, why did you decided to switch from `Object.keys(pkg.dependencies)` to manually defining this vendor packages in config.js ?

thanks.

**Comment by egoist** [comment]
See https://github.com/egoist/vuepack/blob/master/template/build/config.js#L6, it's already updated, maybe you're using an outdated vuepack.

Splitting vendor code because those dependencies would rarely change, bundle them in a single file for a better browser/server caching.

**Comment by dodas** [comment]
What should I see in config? I see there is an manually defined `vendor` array. In previous versions it used to be grabbed from package.json.

**Comment by egoist** [comment]
@dodas Oops, I just misunderstood. 

I want it to be safe by default, so I think it should be manually defined. There's an edge case that there're some dependencies in `package.json` but user does not import them in the app, those dependencies will still be bundled into `vendor.js`, which is unexpected.

**Comment by dodas** [comment]
Sorry, I can't think of a case when one would want to have some package listed in package dependencies, but does not need it in bundle.

Can you?

**Comment by egoist** [comment]
Forgot to remove from package.json 😂

**Comment by dodas** [comment]
I always use `-D` and `-S` for this reason. I dont know, probably there is some need for this, otherwise npm would do this by default.

**Comment by egoist** [comment]
It also means forgot to `npm r -S xxx`, it's not a critical issue, you can always change it to `Object.keys(pkg.dependencies)`

I'm not so sure about this, maybe change it back to this at some point
