### ISSUE TITLE
File loader doesn't work?

### ISSUE THREAD

**Issue by dodas** [egoist/vuepack#44]
Hi, loading static files does not seem to work for me.
I am not sure If I am using it correctly. Example:

```
// App.vue
<div id="app" style="background-image: url('../imgs/bg.jpg')">
```

and I create folder `imgs` in `client` and put `bg.jpg` here.
Webpack dev server does return index.html for this path and production build does not include these files.

Am I missing something? Thanks.

**Comment by egoist** [comment]
Ehh, Webpack won't parse css in Vue template. Just set that in `<style>` section.
