### ISSUE TITLE
Would you be open to a PR for e2e tests and another for unit tests?

### ISSUE THREAD

**Issue by chopfitzroy** [egoist/vuepack#46]
Hey I am extending a local vuepack install to use:
- [Nightwatch.js](http://nightwatchjs.org/) for e2e testing.
- [Karma](https://karma-runner.github.io/1.0/index.html) and [Jasmine](http://jasmine.github.io/) for unit testing.

I was wondering if it would be worth putting a PR together is that something you would be interested in?

Cheers.

**Comment by egoist** [comment]
It's great if you can make this happen, it could be an option in `meta.json`.

**Comment by chopfitzroy** [comment]
Sweet as closing for now will submit PR once everything is done :)

**Comment by mikemassari** [comment]
Any news on this? I am trying to make Karma/Jasmine and Nightwatch work with Vuepack but I'm having quite an hard time

**Comment by chopfitzroy** [comment]
Hey @Michelemassari,

Sorry I have not done any work on this in some time.

Will let you know if I get back on to it.

Cheers,
