### ISSUE TITLE
找不到 babel-core

### ISSUE THREAD

**Issue by mobailabs** [egoist/vuepack#47]
`npm run dev`的时候,找不到这个`babel-core`.

![image](https://cloud.githubusercontent.com/assets/1415418/18949246/1dc60068-866d-11e6-8e2a-b04e750f5e5d.png)

安装 `npm install babel-core --save`后,正常,但是还有问题.

`npm run build`的时候,出现这样的错误.  node v6
![image](https://cloud.githubusercontent.com/assets/1415418/18949302/598fcffc-866d-11e6-91fb-6d5d9510a9c1.png)

**Comment by egoist** [comment]
`babel-core` 已经修复了, https://github.com/egoist/vuepack/commit/c1f222a186bb05273932a6773074ba8abec32a7e.

这个应该装到 `devDependencies`, 因为 `dependencies` 里的依赖都会被打包进单独的 `vendor.js`

**Comment by mobailabs** [comment]
electron 的怎么打包呢

**Comment by egoist** [comment]
还是 npm run build 啊

**Comment by mobailabs** [comment]
![image](https://cloud.githubusercontent.com/assets/1415418/18950787/4e4339e8-8674-11e6-8a51-3fba6061f078.png)
执行了,没有生成 exe 文件

**Comment by egoist** [comment]
这只是打包 client 端的文件，打包可执行文件需要 `electron-packager` https://github.com/electron-userland/electron-packager

**Comment by mobailabs** [comment]
明白了.

**Comment by mobailabs** [comment]
tks
