### ISSUE TITLE
[Question] Does vuepack support both a web-based platform and Electron in the same app?

### ISSUE THREAD

**Issue by nicklaw5** [egoist/vuepack#48]
I have worked with [nwjs.io](http://nwjs.io/) in the past which has allowed me to produce a single app repository that I was able to deploy to the web as well as deploy as a desktop app. [See here](https://github.com/nicklaw5/stryve)

Does vuepack support both a web-based platform and Electron in the same app? Or do I have to maintain two repositories (one for web and electron) if I want to deploy the application as both a web and a desktop application?

**Comment by egoist** [comment]
Yep, but only if you didn't use electron api in your web app, otherwise it will throw errors. You can also use something like `if (isElectron) do this else do that`.
