### ISSUE TITLE
[Question] Three dots in new Vue({})

### ISSUE THREAD

**Issue by aronsuarez** [egoist/vuepack#49]
Hi there,

What is this three dots in the new Vue()?

```
const app = new Vue({
  router,
  store,
  ...App
})
```

Thank you for clarification.

**Comment by egoist** [comment]
Check out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by aronsuarez** [comment]
Thank you, cool stuff
