### ISSUE TITLE
deprecation: electron-prebuilt has been renamed to electron

### ISSUE THREAD

**Issue by kristianmandrup** [egoist/vuepack#51]
When running `npm i` after generating project using template:

```
deprecated electron-prebuilt@1.4.2: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
```

**Comment by kristianmandrup** [comment]
As of version `1.3.1`, we have begun publishing `electron` and `electron-prebuilt` packages to `npm` in tandem. The two packages are identical. We chose to continue publishing the package under both names for a while so as not to inconvenience the thousands of developers who are currently using `electron-prebuilt` in their projects. We recommend updating your `package.json` files to use the new electron dependency, but we will continue releasing new versions of `electron-prebuilt` until the _end of 2016_.

**Comment by egoist** [comment]
Thanks, updated.
