### ISSUE TITLE
Upgrade to vue2

### ISSUE THREAD

**Issue by kristianmandrup** [egoist/vuepack#52]
```
  "dependencies": {
    "vue": "^2.0.0",
    "vue-router": "^2.0.0",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
  },
```

Also latest webpack is now: `"webpack": "2.1.0-beta.25"`

**Comment by egoist** [comment]
webpack has breaking changes since version 2.1.0-beta.22, lack of docs, not compatible with many loaders,  so I will not update it for a while.

**Comment by kristianmandrup** [comment]
Oh!? I had no idea. Thanks ;)

**Comment by kristianmandrup** [comment]
Trying to use a similar approach in a vue component created using a generator:
Getting this error:

``` bash
Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     }
```

You seen this before? Is this the webpack issue you are talking about? I see you are also using the `vue` config option in `webpack.base.config.js`

``` js
module.exports = {
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel',
            exclude: /node_modules/
        }, {
            test: /\.vue$/,
            loaders: ['vue']
        }]
    },
    vue: {
        loaders: {},
    }
};
```

https://github.com/kristianmandrup/circle-menu

``` bash
    "vue-loader": "^9.5.1",
    "vue-style-loader": "^1.0.0",
    "webpack": "2.1.0-beta.21",
    "webpack-dev-middleware": "^1.8.1",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-dashboard": "^0.1.8",
    "webpack-dev-server": "^1.15.0",
    "webpack-merge": "^0.14.1"
```

**Comment by kristianmandrup** [comment]
Related to this issue: https://github.com/webpack/webpack/issues/3018

But I don't see your vue loader config having any real effect unless I'd want to use postcss.

**Comment by egoist** [comment]
PR welcome for webpack 2 beta 23+ :)

**Comment by kristianmandrup** [comment]
Looks like I have beta25 installed and it works just fine...

**Comment by ghost** [comment]
no @kristianmandrup  i try in my i got error

throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration has an unknown property 'vue'. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in configuration.
   Loaders should be updated to allow passing options via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       // test: /.xxx$/, // may apply this only for some modules
       options: {
         vue: ...
       }
     })
   }
- configuration.resolve.extensions[0] should not be empty.
  at webpack (node_modules/webpack/lib/webpack.js:16:9)
  at Object.<anonymous> (/build/server.js:17:18)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:148:18)
  at node.js:405:3

**Comment by kristianmandrup** [comment]
Remove the part `vue` config part:

```
    vue: {
        loaders: {},
    }
```

Se my [circle-menu](https://github.com/kristianmandrup/circle-menu) config

**Comment by egoist** [comment]
I will update webpack when its docs are ready.

**Comment by feusebio** [comment]
I changed version in package.json to "webpack": "^1.12.2" and webpack worked well. The newer versions didn't work, i don't know why:
> 
_$ webpack
Hash: a3e1a8f40ab9ed1a8b16
Version: webpack 1.15.0
Time: 2985ms
   Asset    Size  Chunks             Chunk Names
build.js  213 kB       0  [emitted]  main
    + 10 hidden modules_

**Comment by robertjchristian** [comment]
Could be conflicts in node_modules folder.  Good idea to make sure it's clean.

Try:

`rm -rf node_modules && npm install`
