### ISSUE TITLE
Cannot GET / on http://localhost:4000/

### ISSUE THREAD

**Issue by kxxoling** [egoist/vuepack#58]
I've just created a new project with vuepack without editing any file, and run `npm run dev` after `npm i` finished. But got this error.

**Comment by egoist** [comment]
Ah, awkward, it works for me

**Comment by kxxoling** [comment]
@egoist Have you done any configuration?

**Comment by kxxoling** [comment]
@egoist I checked Electron support either, I guess this matters, so I recreated a new project without Electron support, and it works this time!

So is it a bug that web support and Electron support cannot works at the same time?

**Comment by egoist** [comment]
It's not a bug, if you are using Electron it will directly serve [app/dist/index.html](https://github.com/egoist/vuepack/blob/master/template/app/index.js#L19) instead of loading the remote one (http://localhost:4000/index.html) because of some limitations.

And I guess you will rarely visit `http://localhost:4000` in browser either, because your app may use Electron specified API.

**Comment by kxxoling** [comment]
@egoist But there's still have `client` folder on the side of `app`. Isn't it mean to support web development as well as Electron?

**Comment by egoist** [comment]
Entry file in `client` folder is built to use in your Electron app

**Comment by kxxoling** [comment]
@egoist I thought that was used for web development and `app` is used for Electron, because `app` is the extra folder compared to web project.

So, is there any way to start a new project for both web an Electron?

**Comment by egoist** [comment]
@kxxoling there will always be two parts in a typical electron app, `app` for main process, `client` for renderer process, do you mean you wanna build an electron as well as a website which user can access via browser? If so I'd recommend you to separate them into two projects 🤔

**Comment by kxxoling** [comment]
@egoist They may contains a lot of similar components and actions, it would be better to live in one  project to share components. It could rather similar to `component.ios.js` and `component.android.js` in react-native.
