### ISSUE TITLE
[Vue warn]: Failed to resolve directive: link  (found in anonymous component - use the "name" option for better debugging messages.)

### ISSUE THREAD

**Issue by wanteed-lh** [egoist/vuepack#59]
/*******\* index.js***************/
var Vue = require('vue/dist/vue.js');
//import Vue from 'vue/dist/vue.js'
var VueRouter = require('vue-route');

Vue.use(VueRouter);
 var CHATBOX = require('./compnent/chatbox/chatbox.vue');
var ADDROOMS = require('./compnent/rooms/add_rooms.vue');
var ALLROOMS = require('./compnent/rooms/all_rooms.vue');
var MYROOMS = require('./compnent/rooms/my_rooms.vue');
new Vue ({
    el:"#app-layout",
    data: function () {
        return{
        msg:"hello",  
        }
    }
});
var App = Vue.extend({});
let router = new VueRouter();
router.map({
    '/addrooms': {
        component: ADDROOMS
    },
    '/allrooms': {
        component: ALLROOMS
    },
    '/myrooms': {
        component: MYROOMS
    },
    '/chatbox': {
        component: CHATBOX
    },
});
/*********************_home.blade . php ***_**************/

<div class="row" id="app-layout">
  <a v-link="{ path: '/addrooms' }">.......</a>
        @{{ msg }}
         <router-view></router-view>
   
    </div>

/************************\* add_rooms.vue******************/
<template>
    <div v-loading="loading (Boolean)" :loading-options="{ options }">

```
            <input type="text" name="name" class="form-control" v-model="room_name">

            <input type="submit" @click="addRoom()" name="" value="add room">

  >   
</div>
```

</template>

<script>
import loading from 'vue-loading';
import MessageBox from 'vue-msgbox';
    export default{
        directives: { loading },
        data: function (){
            return{
                room_name:"",
                isLoading:false,
            }
        },
        methods:{
            addRoom: function (){
                this.isLoading = true ;
                MessageBox("Good job!", "You clicked the button!", "success");// title, message, type
            }
        }
    }
</script>

/******************************_package.jsnom**_*******************/
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "babel-core": "^6.18.0",
    "babel-preset-es2015": "^6.18.0",
    "bootstrap-sass": "^3.0.0",
    "browserify": "^13.1.1",
    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-vueify": "^2.0.0",
    "vue": "^2.0.3",
    "vue-loading": "^0.1.4",
    "vue-msgbox": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-route": "^1.5.1",
    "vueify": "^9.2.4"
  },
  "dependencies": {
    "vue-msgbox": "^2.0.1"
  }
}

**Comment by egoist** [comment]
you should use vue-router 2

**Comment by wanteed-lh** [comment]
thanks its work
