### ISSUE TITLE
"npm run build" says "...window is not defined...", pls help

### ISSUE THREAD

**Issue by mclxly** [egoist/vuepack#60]
ERROR in ./client/components/App/style.css
Module build failed: ReferenceError: window is not defined
    at .../node_modules/style-loader/index.js!

btw, "npm run dev" works well

**Comment by egoist** [comment]
can you provide a repro?

**Comment by mclxly** [comment]
I just follow "Get started", nothing changed.

```
$ npm install -g vue-cli
$ vue init egoist/vuepack new-project
$ cd new-project
$ npm install

# edit files and start developing
$ npm run dev
# bundle all scripts and styles for production use
$ npm run build

# lint your code
$ npm run lint
```

**Comment by mclxly** [comment]
@egoist Curiously, today I create a new project and works well. Thank you anyway!

**Comment by egoist** [comment]
This may be related to https://github.com/egoist/vuepack/commit/afbb14afbc525e45ef3f6daf27e971f4a094c032, I unexpectedly added `style-loader` in extract-text-webpack-plugin.

**Comment by mclxly** [comment]
@egoist :+1:
