### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by CalebKester** [egoist/vuepack#64]
I got the demo up and running but it takes about 500ms for the number to increment every time that I click it. I just want to make sure this 500ms lag is normal and not just something on my end.  Is that mostly due to adding vuex to manage the state that it takes longer to update? I was hoping it'd be as responsive as the  clicker found on the vue docs: https://vuejs.org/v2/guide/events.html#Listening-to-Events

**Comment by egoist** [comment]
It's demo for updating data asynchronously in vuex action, maybe I should update this a bit to reduce confusion 😕 https://github.com/egoist/vuepack/blob/master/template/client/store/index.js#L17

**Comment by CalebKester** [comment]
Ah, that makes a lot more sense then. Can't believe i missed that in the source code 👍

**Comment by egoist** [comment]
I've updated the example 😉 http://vuepack.surge.sh

**Comment by CalebKester** [comment]
Thanks! that's great! Could you give me a very very quick explanation to why i should be using async and not the other method? or point me in the right direction? Sorry i'm pretty new to this stuff.

**Comment by egoist** [comment]
You can checkout the [reddit discussion](https://www.reddit.com/r/vuejs/comments/5do7u8/vuex_why_have_mutations_and_actions/) and  https://github.com/vuejs/vuex/issues/236
