### ISSUE TITLE
Upgrade to webpack@2.1.0-beta.27

### ISSUE THREAD

**Issue by egoist** [egoist/vuepack#65]
Webpack 2 docs are almost ready, https://webpack.js.org/

Anyone would like to help? Should be easy now!

**Comment by ryanmclaughlin** [comment]
This would be nice 👍  (I would help if I knew more about webpack).

**Comment by sotaan** [comment]
I can't promise anything but since I played a lot with the `webpack.*` config files this week, I might give it a try this week-end.

**Comment by skyrpex** [comment]
There is a RC version already :facepunch:

**Comment by egoist** [comment]
Done https://github.com/egoist/vuepack/releases/tag/v3.0.0-rc.1
