### ISSUE TITLE
How can I use vbuild with this template?

### ISSUE THREAD

**Issue by ryanmclaughlin** [egoist/vuepack#66]
Hi there,

How can I use vbuild with this template? A little confused with whether I need webpack and all the other addons in package.json or not?

**Comment by egoist** [comment]
Sure you don't need them, you can remove all `devDependencies` in package.json and even `vue` in `dependencies`. The `./build` dir is no longer needed too. Then `vbuild ./client -d` is good to go.

**Comment by egoist** [comment]
You can check out https://github.com/egoist/vbuild/tree/master/template for default template, it's nothing different from a normal Vue app, except for no build config to manage. It's easy to make your own template using `vue-cli` and work with `vbuild` too.
