### ISSUE TITLE
Example only working with es6+ browsers?

### ISSUE THREAD

**Issue by mindbits** [egoist/vuepack#67]
Hello, 

I thought that babel would take care of the transpiliing but already the small example is not working in non-es6 browsers. 

Which settings would need to be changed? 

Ty

**Comment by egoist** [comment]
I think the bundled files are transpiled to es5 already?

**Comment by mindbits** [comment]
npm run build -> works like charm in modern browsers but non-es6 browsers fail, so I am not sure if I need to set an additional flag somewhere in the webpack config?

**Comment by egoist** [comment]
Can you provide some error messages?

**Comment by egoist** [comment]
I got this, `vuex` requires a Promise polyfill.

<img width="519" alt="2016-11-29 1 12 18" src="https://cloud.githubusercontent.com/assets/8784712/20678246/f5bfedb6-b5d0-11e6-94a6-6520908085da.png">

**Comment by mindbits** [comment]
oh great that you found it. thank you

**Comment by egoist** [comment]
The template has been updated with a default Promise polyfill 🎉
