### ISSUE TITLE
`npm run dev` gives "Cannot GET /"

### ISSUE THREAD

**Issue by oskarhane** [egoist/vuepack#69]
After I followed all install instructions (using node v.4.47 and v.7.20, same for both) I run `npm run dev` and all looks green (web pack saying `webpack: bundle is now VALID`).
When opening `http://localhost:4000` in a web browser I get "Cannot GET /".

On MacOS Sierra.
No to JSX support vue-cli config.
Yes to electron in vue-cli config.

Any pointers?

I've tried to remove `node_modules` and run installation again, with the same result.

**Comment by oskarhane** [comment]
It works as expected when not adding electron support in the vue-cli config.

**Comment by egoist** [comment]
Sure, just don't open http://localhost:4000 then, since you're building an electron app.

**Comment by oskarhane** [comment]
Oh, `npm run dev` is not supposed to work when electron support is enabled?  
That should be more clear in the README then, since that's how I interpret it here: https://github.com/egoist/vuepack/blob/master/docs/electron.md

**Comment by egoist** [comment]
I've enabled the html output for Electron mode in dev server, but you'll still get a `require is not defined` error. [doc](https://github.com/egoist/vuepack/blob/master/docs/electron.md) has been updated for this.
