### ISSUE TITLE
 Demo can't run with an error

### ISSUE THREAD

**Issue by pookpal** [egoist/vuepack#72]
when run 'npm run dev'，I can't request http://locahost:4000；error  as follows;

and i also can not  packgage this app using electron-packager

![image](https://cloud.githubusercontent.com/assets/10249353/21003399/15add51a-bd66-11e6-89f5-93a12f072f6d.png)

**Comment by egoist** [comment]
How's it supposed to run in browser? I guess it's in electron mode, just run `npm run app` to open The app
