### ISSUE TITLE
Handling images

### ISSUE THREAD

**Issue by jancel** [egoist/vuepack#77]
I see this in the build, but don't see any documentation on adding files to the apps (and how to point at them.  Is there somewhere I'm missing this?

```
        test: /\.(ico|jpg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
        loader: 'file',
        query: {
          name: 'static/media/[name].[hash:8].[ext]'
        }
```

**Comment by egoist** [comment]
I will add some docs about this later, but could the doc of [file-loader](https://github.com/webpack/file-loader) help for now?

**Comment by egoist** [comment]
See https://github.com/egoist/vuepack/blob/master/docs/static-files.md

**Comment by jancel** [comment]
Sweet.  Thanks a ton.
