### ISSUE TITLE
How to enable Sass with sourcemap?

### ISSUE THREAD

**Issue by sajadabedi** [egoist/vuepack#78]
I want to have scss for styling with sourcemap so I can debug it in browser if needed.
How I can do enable scss with sourcemap?

Thank you.

**Comment by egoist** [comment]
I've added this https://github.com/egoist/vuepack/commit/00e05758254d724443c948d4009f59fde6df02f6

**Comment by sajadabedi** [comment]
I added those change to utils.js file but still I can't use sass!

**Comment by egoist** [comment]
what's the error?

**Comment by sajadabedi** [comment]
@egoist when I rename the style.css to style.scss also added to the index.js this error print on terminal.
```
ERROR in ./client/components/Counter/style.scss
Module parse failed: /Users/sajad/Sites/vuejs/client/components/Counter/style.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .counter {
|   margin: 100px auto;
|   border-radius: 3px;
 @ ./client/components/Counter/index.js 1:0-33
 @ ./client/views/Home/index.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi client
```

**Comment by egoist** [comment]
You should use scss in single file component, otherwise add `sass-loader` to the webpack config.

**Comment by ryanmclaughlin** [comment]
> You should use scss in single file component, otherwise add sass-loader to the webpack config.

@egoist Any tips on how to do this? I used to have this in `webpack.base.js`: 

```
  vue: {
    loaders: {
      sass: "vue-style-loader!css-loader!sass?indentedSyntax"
    },
  },
```

But this doesn't seem to work anymore: 
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
```

**Comment by egoist** [comment]
@ryanmclaughlin sass-loader is already added for single file component, btw we're using webpack 2.2.0-rc.1 now

**Comment by ryanmclaughlin** [comment]
> @ryanmclaughlin sass-loader is already added for single file component, btw we're using webpack 2.2.0-rc.1 now

Thanks for that! I updated it :)

Hrm, for some reason I'm getting:

```
ERROR in ./~/css-loader?sourceMap&-autoprefixer?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-c87e08b0&scoped=true!./~/sass-loader?sourceMap!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/views/Home.vue
Module build failed: 
<template>
^
      Invalid CSS after "": expected 1 selector or at-rule, was "li:hover"
      in /Users/mack/Projects/gamewatch/client/views/Home.vue (line 1, column 1)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-c87e08b0&scoped=true!./~/sass-loader?sourceMap!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/views/Home.vue 4:14-317 13:2-17:4 14:20-323
 @ ./client/views/Home.vue
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi client
```

Using `<style lang="sass" scoped>`

**Comment by egoist** [comment]
@ryanmclaughlin open new issue with repro steps
