### ISSUE TITLE
Error: Not allowed to load local resource

### ISSUE THREAD

**Issue by jsnelgro** [egoist/vuepack#79]
After building with electron support, I start the server using `npm run dev`, then open electron with `npm run app` in a new shell, but get `Not allowed to load local resource: file:///Users/myusername/myappname/app/dist/index.html` in the electron window dev console.

electron version: `1.4.7`
node version: `6.3.1`

thanks for any help!

**Comment by egoist** [comment]
fixed, I changed it to load index.html from `http://localhost:4000` in dev mode
