### ISSUE TITLE
using request or vue resource?

### ISSUE THREAD

**Issue by paOol** [egoist/vuepack#82]
this is  more of a generic `npm i {{package}}` question.

trying to use https://github.com/pagekit/vue-resource

installed it , but when i try this in my component,  
```
  this.$http.get('/http://google.com', 
```
i get
`Uncaught TypeError: Cannot read property 'get' of undefined`

I've tried putting 
`import vue-resource from 'vue-resource';` in various places. all incorrectly.

what is the correct usage of npm libraries in vue?

**Comment by paOol** [comment]
found it.
`client/router/index.js`

```
import VueResource from 'vue-resource'
import Home from '../views/Home'

Vue.use(Router);
Vue.use(VueResource);
```

was able to get it working with this.

**Comment by egoist** [comment]
I use `axios` personally 😀
