### ISSUE TITLE
为什么没有hot reload 呢？试了两次都没发现？？？

### ISSUE THREAD

**Issue by cddsgtc** [egoist/vuepack#85]

**Comment by cddsgtc** [comment]
why  hot reload don't work?
i just ignore the jax function

**Comment by egoist** [comment]
能提供有用的信息吗

**Comment by cddsgtc** [comment]
@egoist 今天好怪，连都连不上了。。。
![图](http://chuantu.biz/t5/44/1483163160x1928877036.jpg)

**Comment by egoist** [comment]
现在可以用 sao 安装 https://github.com/egoist/vuepack#sao

**Comment by cddsgtc** [comment]
@谢谢，问题已找到是host的问题。
