### ISSUE TITLE
postcss is no display chrome prefix

### ISSUE THREAD

**Issue by ynanzero** [egoist/vuepack#86]
```
<style type="text/css">
body{
  display: -ms-flexbox;
  display: flex;
}
</style>
```
>and how can i change css to less, like component/home/index
```
import './style.less' //like this
export default {
}
```

**Comment by egoist** [comment]
we're using `last 2 versions` as autoprefixer option, so that doesn't need a prefix for chrome?

> and how can i change css to less, like component/home/index

add less loader in webpack.dev.js and extract-text-webpack-plugin in webpack.prod.js

**Comment by ynanzero** [comment]
>...... too late , but thank you

>i find the answer from other places.

>change like this browsers: ['last 5 versions', 'ie > 8'] ,  it work too

>and change .less file , i just change test: /\.css$/, to  test: /\.less$/, ,it work fine ,is that right ?

>and i find out other issues , but i just forgot what problem, but i remember how to fixed that 

>update to webpack version "webpack": "2.2.0-rc.1"  to  "webpack": "2.2.0-rc.2"

**Comment by ynanzero** [comment]
ok ..! now i have new error , 
can you gave a example for .less load  ?

**Comment by egoist** [comment]
check out https://github.com/egoist/vuepack/commit/01af2df3af149bdb85d4607f8e640c2072844eef I've added this

**Comment by ynanzero** [comment]
but now is not prefix

```
<style type="text/css">
body {
  display: flex;
}
</style>
```

**Comment by egoist** [comment]
fixed https://github.com/egoist/vuepack/commit/464781672cfe9bcf072421aa0df3b188151b6c74 , we should add postcss-loader too

**Comment by ynanzero** [comment]
```
webpack.prod.js:62 
 fallbackLoader: 'style-loader'
```

**Comment by egoist** [comment]
my bad, fixed

**Comment by ynanzero** [comment]
```
 loader: [_.cssLoader].concat(loaders,
                fallbackLoader: 'style-loader'
})
```
my ide gave me error

**Comment by ynanzero** [comment]
```
\webpack.prod.js:62
                fallbackLoader: 'style-loader')
                ^^^^^^^^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext 
```

**Comment by ynanzero** [comment]
>i just download you new package ,  but less stll not work ,

>with npm run dev
> error:
><code >This dependency was not found in node_modules:</code>
>  <code >*./style.less</code>
-
>with npm run build
>error
><code>Module not found: Error: Can't resolve 'less-loader' in 'D:\example </code>

**Comment by egoist** [comment]
install less-loader first

**Comment by ynanzero** [comment]
哈哈,thank you very much ! you are the best!

**Comment by ynanzero** [comment]
### whoops ! is has new problem ,
<pre>ERROR in ./~/less-loader/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\example\node_modules\less-loader'
 @ ./~/less-loader/index.js 9:9-22
 @ multi vendor</pre>

**>But** the strange thing is npm run build success. the css file it package what i want
