### ISSUE TITLE
Empty Warning Message with Webpack 2.2.0-rc.4

### ISSUE THREAD

**Issue by DotCoyote** [egoist/vuepack#94]
I upgraded to the latest RC4 of Webpack, now I get an empty warning and don't know where to debug ;)

<img width="573" alt="iterm" src="https://cloud.githubusercontent.com/assets/3854991/21885741/5317efda-d8b9-11e6-9ad0-a7ec56e129f9.png">

Works fine with RC3

**Comment by egoist** [comment]
Is there warning when you run `npm run build`?

You can remove https://github.com/egoist/vuepack/blob/master/template/build/server.js#L36 to get  full log

Currently it's using [friendly-errors-webpack-plugin](https://github.com/geowarin/friendly-errors-webpack-plugin) to display logs

**Comment by DotCoyote** [comment]
Build runs perfectly, removing the quiet-option gives me:

`WARNING in webpack: Using NoErrorsPlugin is deprecated. Use NoEmitOnErrorsPlugin instead.`

**Comment by egoist** [comment]
just rename that plugin then 😃

**Comment by DotCoyote** [comment]
Done :)
Didn't know it was that easy (Webpack's still a mystery...)

But you could update that in your repository as well :P

**Comment by egoist** [comment]
Fixed.

**Comment by mithun810** [comment]
@egoist How and where do i rename the plugin?

**Comment by egoist** [comment]
@mithun810 it's fixed, if you are using older vuepack, try searching `NoErrorsPlugin` in your project

**Comment by mithun810** [comment]
@egoist i am actually not using vuepack so could you tell me where to change this plugin name
would be a great help thanks

**Comment by egoist** [comment]
@mithun810 the same way :P

**Comment by mithun810** [comment]
haha Thankyou Very Helpful!!!!
